### ISSUE TITLE
Support Group By Aggregation Queries

### ISSUE THREAD

**Issue by Max-Meldrum** [uwheel/datafusion-uwheel#13]
Optimize the following type of queries by using [group_by](https://docs.rs/uwheel/latest/uwheel/wheels/read/hierarchical/struct.Haw.html#method.group_by) to group aggregates by an interval (e.g., hours, days).

```sql
SELECT
    date_trunc('day', timestamp) as day,
    COUNT(*) as count
FROM
    table
WHERE
    timestamp >= {} AND timestamp < {}
GROUP BY
    date_trunc('day', timestamp)
ORDER BY
    day

```

**Comment by LYZJU2019** [comment]
Let me have a try :-)
